import crypto from 'node:crypto';
import { db,json,normalized,verifyAdminJWT,verifyUserJWT } from './_admin-core.mjs';
const BUCKET='payment-receipts';
const clean=(v,n=500)=>String(v??'').trim().replace(/[<>]/gu,'').slice(0,n);const cleanField=(field,index)=>({id:clean(field?.id||`field-${index}`,100),label:clean(field?.label||'حقل',120),type:['text','number','tel','email','textarea','select'].includes(field?.type)?field.type:'text',placeholder:clean(field?.placeholder,200),required:field?.required===true,order:Number(field?.order||index+1),options:Array.isArray(field?.options)?field.options.slice(0,50).map(v=>clean(v,100)):[]});
const requestId=()=>`DEP-${Date.now()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
const uploadReceipt=async(dataUrl,userId,id)=>{if(!dataUrl)return'';const m=String(dataUrl).match(/^data:(image\/(?:jpeg|png|webp));base64,(.+)$/su);if(!m)throw new Error('صورة الإشعار غير صالحة');const bytes=Buffer.from(m[2],'base64');if(bytes.length>5*1024*1024)throw new Error('صورة الإشعار أكبر من 5 MB');const ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[m[1]],path=`${userId}/${id}.${ext}`,key=process.env.SUPABASE_SERVICE_ROLE_KEY,url=process.env.SUPABASE_URL,r=await fetch(`${url}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{apikey:key,authorization:`Bearer ${key}`,'content-type':m[1],'x-upsert':'false'},body:bytes});if(!r.ok)throw new Error('تعذر حفظ إشعار التحويل');return path;};
const notify=async(userId,title,message,type='info',link='')=>{const id=`NOT-${Date.now()}-${crypto.randomBytes(4).toString('hex')}`;await db.upsert('notifications',id,{id,userId,title,message,type,link,read:false,createdAt:new Date().toISOString()});};
export const handler=async(event)=>{if(event.httpMethod!=='POST')return json(405,{error:'Method not allowed'});try{const body=JSON.parse(event.body||'{}'),action=String(body.action||'');
 if(action==='public-config'){const [methods,settings]=await Promise.all([normalized.list('deposit_methods'),normalized.get('settings','deposit_page')]);return json(200,{ok:true,methods:methods.filter(m=>m.enabled!==false).sort((a,b)=>Number(a.order||0)-Number(b.order||0)),settings:settings||{}});}
 if(action==='user-create'){const user=await verifyUserJWT(event);if(!user)return json(401,{error:'يجب تسجيل الدخول'});const profile=await normalized.get('users',user.id);if(!profile||!['verified','active'].includes(profile.accountStatus))return json(403,{error:'يجب توثيق رقم الهاتف أولًا'});const method=await normalized.get('deposit_methods',String(body.methodId||''));if(!method||method.enabled===false)return json(400,{error:'طريقة الإيداع غير متاحة'});const idem=clean(body.idempotencyKey,120);if(!idem)return json(400,{error:'معرف العملية مطلوب'});const exists=(await normalized.list('deposit_requests')).find(r=>r.userId===user.id&&r.idempotencyKey===idem);if(exists)return json(200,{ok:true,result:exists,duplicate:true});const amount=Number(body.amount||0),min=Number(method.minAmount||0),max=Number(method.maxAmount||1e12);if(!Number.isFinite(amount)||amount<min||amount>max)return json(400,{error:'المبلغ خارج الحدود المسموحة'});const id=requestId(),receiptPath=await uploadReceipt(body.receiptData,user.id,id),now=new Date().toISOString(),request={id,userId:user.id,userName:profile.name||'',userPhone:profile.phone||'',methodId:method.id,methodName:method.name,amount,currency:clean(body.currency||method.currency||'YER',10),fields:body.fields&&typeof body.fields==='object'?body.fields:{},receiptPath,notes:clean(body.notes,1000),idempotencyKey:idem,status:'pending',createdAt:now,updatedAt:now};await db.upsert('deposit_requests',id,request);await notify(user.id,'تم استلام طلب التغذية','طلبك قيد المراجعة','pending',`reports.html?deposit=${id}`);return json(200,{ok:true,result:request});}
 if(action==='user-list'){const user=await verifyUserJWT(event);if(!user)return json(401,{error:'يجب تسجيل الدخول'});const rows=await normalized.list('deposit_requests');return json(200,{ok:true,items:rows.filter(r=>r.userId===user.id).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))});}
 if(action==='admin-list'){if(!await verifyAdminJWT(event))return json(403,{error:'صلاحية المدير مطلوبة'});const rows=await normalized.list('deposit_requests');return json(200,{ok:true,items:rows.sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt))});}
 if(action==='admin-save-method'){if(!await verifyAdminJWT(event))return json(403,{error:'صلاحية المدير مطلوبة'});const method={...(body.method||{}),id:clean(body.method?.id||`method-${Date.now()}`,100),name:clean(body.method?.name,100),accountNumber:clean(body.method?.accountNumber,120),accountName:clean(body.method?.accountName,160),instructions:clean(body.method?.instructions,1500),enabled:body.method?.enabled!==false,receiptRequired:body.method?.receiptRequired!==false,autoCredit:body.method?.autoCredit===true,order:Number(body.method?.order||0),minAmount:Number(body.method?.minAmount||0),maxAmount:Number(body.method?.maxAmount||1e12),currencies:Array.isArray(body.method?.currencies)?body.method.currencies:['YER'],fields:Array.isArray(body.method?.fields)?body.method.fields.slice(0,50).map(cleanField):[]};await db.upsert('deposit_methods',method.id,method);return json(200,{ok:true,result:method});}
 if(action==='admin-delete-method'){if(!await verifyAdminJWT(event))return json(403,{error:'صلاحية المدير مطلوبة'});const id=clean(body.id,100),pending=(await normalized.list('deposit_requests')).some(r=>r.methodId===id&&['pending','processing'].includes(r.status));if(pending)return json(409,{error:'لا يمكن حذف طريقة لديها طلبات معلقة'});await db.remove('deposit_methods',id);return json(200,{ok:true});}
 if(action==='admin-update'){const admin=await verifyAdminJWT(event);if(!admin)return json(403,{error:'صلاحية المدير مطلوبة'});const id=clean(body.id,120),req=await normalized.get('deposit_requests',id);if(!req)return json(404,{error:'الطلب غير موجود'});const status=['pending','processing','approved','completed','rejected'].includes(body.status)?body.status:req.status,approvedAmount=Number(body.approvedAmount??req.approvedAmount??req.amount),now=new Date().toISOString();if(['approved','completed'].includes(status)&&body.creditBalance===true&&!req.credited){const balance=await normalized.get('user_balances',req.userId);await db.upsert('user_balances',req.userId,{...(balance||{}),userId:req.userId,balance:Number(balance?.balance||0)+approvedAmount,updatedAt:now});req.credited=true;}const saved={...req,status,approvedAmount,rejectionReason:status==='rejected'?clean(body.reason,500):'',adminNotes:clean(body.adminNotes,1000),processedBy:admin.id,processedAt:now,updatedAt:now};delete saved.id;await db.upsert('deposit_requests',id,saved);await notify(req.userId,status==='rejected'?'تم رفض طلب التغذية':'تم تحديث طلب التغذية',status==='rejected'?(saved.rejectionReason||'تم رفض الطلب'):`حالة طلبك: ${status}`,status,`reports.html?deposit=${id}`);return json(200,{ok:true,result:{id,...saved}});}
 return json(400,{error:'عملية غير معروفة'});}catch(error){console.error('[deposit-api]',error);return json(500,{error:error.message||'تعذر تنفيذ العملية'});}};
